We will be looking at data from the [Austin Animal Center](
https://data.austintexas.gov/Health-and-Community-Services/Austin-Animal-Center-Outcomes-10-01-2013-to-05-05-/9t4d-g238/about_data)

The JSON file we use below directly pulls the first 1000 animals that left the center.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# could instead also say from matplotlib import pyplot as plt

# import animal shelter data
json_url = 'https://data.austintexas.gov/resource/9t4d-g238.json'
animals_df = pd.read_json(json_url)
animals_df.head()

,animal_id,date_of_birth,datetime,monthyear,outcome_type,outcome_subtype,animal_type,sex_upon_outcome,age_upon_outcome,breed,color,name
0,A668305,2012-12-01,2013-12-02 00:00:00-05:00,12-2013,Transfer,Partner,Other,Unknown,1 year,Turtle Mix,Brown/Yellow,NaN
1,A673335,2012-02-22,2014-02-22 00:00:00-05:00,02-2014,Euthanasia,Suffering,Other,Unknown,2 years,Raccoon,Black/Gray,NaN
2,A675999,2013-04-03,2014-04-07 00:00:00-05:00,04-2014,Transfer,Partner,Other,Unknown,1 year,Turtle Mix,Green,NaN
3,A679066,2014-04-16,2014-05-16 00:00:00-05:00,05-2014,NaN,NaN,Other,Unknown,4 weeks,Rabbit Sh,Brown,NaN
4,A680855,2014-05-25,2014-06-10 00:00:00-05:00,06-2014,Transfer,Partner,Bird,Unknown,2 weeks,Duck,Yellow/Black,NaN

### Basic EDA

In [2]:
# get general information about the dataset using .info()
animals_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   animal_id         1000 non-null   object
 1   date_of_birth     1000 non-null   object
 2   datetime          1000 non-null   datetime64[ns, UTC-05:00]
 3   monthyear         1000 non-null   object
 4   outcome_type      999 non-null    object
 5   outcome_subtype   801 non-null    object
 6   animal_type       1000 non-null   object
 7   sex_upon_outcome  1000 non-null   object
 8   age_upon_outcome  1000 non-null   object
 9   breed             1000 non-null   object
 10  color             1000 non-null   object
 11  name              762 non-null    object
dtypes: datetime64[ns, UTC-05:00](1), object(11)
memory usage: 93.9+ KB

In [3]:
# use the .describe() function to get more information
animals_df.describe()

,animal_id,date_of_birth,datetime,monthyear,outcome_type,outcome_subtype,animal_type,sex_upon_outcome,age_upon_outcome,breed,color,name
count,1000,1000,1000,1000,999,801,1000,1000,1000,1000,1000,762
unique,997,664,NaN,29,7,11,5,5,35,200,117,679
top,A724077,2015-04-19,NaN,04-2016,Transfer,Partner,Dog,Neutered Male,1 year,Domestic Shorthair Mix,Black/White,Bella
freq,2,12,NaN,124,771,769,623,336,177,264,109,5
mean,NaN,NaN,2015-12-31 20:45:36-05:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,2013-12-02 00:00:00-05:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,2015-09-11 18:00:00-05:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,2016-02-02 00:00:00-05:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,2016-05-06 00:00:00-05:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,2016-08-17 00:00:00-05:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# find the number of each animal type using .value_counts()
animals_df.value_counts()

animal_id  date_of_birth  datetime                   monthyear  outcome_type  outcome_subtype  animal_type  sex_upon_outcome  age_upon_outcome  breed                      color                name
A433746    2006-04-09     2015-11-04 00:00:00-05:00  11-2015    Transfer      Partner          Dog          Spayed Female     9 years           Australian Shepherd Mix    White/Brown          Evette          1
A720078    2011-02-02     2016-02-15 00:00:00-05:00  02-2016    Transfer      Partner          Dog          Intact Female     5 years           Labrador Retriever Mix     Black                Mary Jane       1
A720169    2015-02-03     2016-02-17 00:00:00-05:00  02-2016    Transfer      Partner          Dog          Spayed Female     1 year            Chihuahua Shorthair Mix    Black/Brown          *Rita           1
A720190    2009-02-04     2016-02-07 00:00:00-05:00  02-2016    Transfer      Partner          Dog          Spayed Female     7 years           Airedale Terrier Mix       Tricolor             Little Missy    1
A720297    2013-02-06     2016-02-10 00:00:00-05:00  02-2016    Transfer      Partner          Dog          Spayed Female     3 years           Pit Bull Mix               Brown                Chica           1
                                                                                                                                                                                                               ..
A710994    2013-08-31     2015-10-21 00:00:00-05:00  10-2015    Transfer      Partner          Dog          Neutered Male     2 years           Bull Terrier               Brown Brindle/White  Bronson         1
A711018    2013-03-01     2016-02-16 00:00:00-05:00  02-2016    Transfer      Partner          Dog          Neutered Male     2 years           Australian Cattle Dog Mix  Brown/White          Milo            1
A711319    2014-09-05     2015-11-11 00:00:00-05:00  11-2015    Transfer      Partner          Cat          Spayed Female     1 year            Domestic Shorthair Mix     Black                *Leah           1
A711463    2015-07-31     2016-02-03 00:00:00-05:00  02-2016    Transfer      Partner          Cat          Neutered Male     6 months          Domestic Shorthair Mix     Black/White          *Gary           1
A754280    2016-07-12     2016-04-11 00:00:00-05:00  04-2016    Transfer      Partner          Dog          Intact Male       0 years           Australian Cattle Dog      Black/Brown          Chewbacca       1
Name: count, Length: 604, dtype: int64

#### With graphs!

In [ ]:
# assign these counts to a new variable, animal_type_counts
animal_type_counts = animals_df['animal_type'].value_counts()

# let's look at a histogram
plt.hist(animals_df["animal_type"])
plt.show()

In [ ]:
# and a horizontal bar chart, because it's fun
plt.barh(animal_type_values.index, width=animal_type_values.values)
plt.show()

In [ ]:
# What does this code do?
mask_other_animals = animals_df['animal_type'] == 'Other'
animals_df[mask_other_animals]['breed'].value_counts()

### Engineering some data

In [ ]:
# How many different genders are represented in our dataset?

In [ ]:
# Function to pare down the number of sexes
def sex_mapper(status):
    if status in ['Neutered Male', 'Intact Male']:
        return 'Male'
    elif status in ['Spayed Female', 'Intact Female']:
        return 'Female'
    else:
        return 'Unknown'

In [ ]:
animals_df['new_sex1'] = animals_df['sex_upon_outcome'].map(sex_mapper)
animals_df[:, ['sex_upon_outcome', 'new_sex1']]

### Filling in missing values
#### With np.nan or "Unknown"

In [ ]:
# Let's remember which columns said there were a lot of missing values

In [ ]:
# Create a copy of the data
animals_clean = animals_df.copy()

# insert np.nan for missing values
animals_name_filled = animals_clean.fillna('np.nan')
animals_name_filled.head()

In [ ]:
# Alternative way to fill missing values by specifying column(s) first
animals_only_names = animals_clean[['name']].fillna(value='UNKNOWN')
animals_only_names.head(5)

Question: Why are we using animals_df[['name']] in the first line of the code rather than just animals_df['name']?

In [ ]:
# Overwrite the existing 'name' column with the new one
animals_clean[['name']] = animals_only_names
animals_clean.head()

#### Or with imputed values

In [ ]:
outcome_subtype_counts = animals_clean['outcome_subtype'].value_counts()
outcome_subtype_counts

In [ ]:
# Gets only the categories in order of most frequent to least frequent
outcome_subtype_ordered = outcome_subtype_counts.index
print(outcome_subtype_ordered)

# And now find the most common one
most_common_outcome_subtype = outcome_subtype_ordered[0]
print(most_common_outcome_subtype)

In [ ]:
# Another way to find this is to use the .mode() function
print(animals_df['outcome_subtype'].mode())

# Note this is Series so we have to get the first element (which is the value)
most_common_outcome_subtype = animals_clean['outcome_subtype'].mode()[0]
most_common_outcome_subtype

In [ ]:
# Similar to the previous subsection, we can use fillna() and update the DF
animals_clean['outcome_subtype'] = animals_clean['outcome_subtype']\
    .fillna(most_common_outcome_subtype)
animals_clean.head()

### Adding "missing values" column

In [ ]:
# Specify the animals that originally had missing "outcome_subtype" values
missing_outcome_subtypes = _______
missing_outcome_subtypes

In [ ]:
# Add this new column to the animals_clean df as column "outcome_subtype_missing"
animals_clean________

### Dropping missing values

In [ ]:
# How many missing values did the outcome_type have?
animals_df['outcome_type'].value_counts().sum()

In [ ]:
# Perhaps we decide it's not worth keeping this one data point around
animals_clean = animals_clean.dropna(axis=0, subset=['outcome_type'])
animals_clean.head()

In [ ]:
# Finally, look at the .info() for both the original and cleaned df!